### ISSUE TITLE
Payment limitations

### ISSUE THREAD

**Issue by alexolkhovskii** [opefitoo/nursev3#19]
We keep all the communication in the Upwork chat, but I thought that it is not a good idea to talk about wire transfers in the Upwork chat, so I'm writing you here :)

If you would like to do not pause development in December, we can discuss an option of direct payment (outside of Upwork) for the December. Please let me know if it is interesting for you.

**Comment by mehditerraneen** [comment]
Hi Alex,
You are right, we should not communicate on this on upwork :)
Do you a google hangout account ?

**Comment by alexolkhovskii** [comment]
Great! :) Sure, here is my google account alex.olkhovskii@gmail.com. I will wait for your message in hangout
