### ISSUE TITLE
An official invoice PDF format should be limited to 20 Prestations max

### ISSUE THREAD

**Issue by mehditerraneen** [opefitoo/nursev3#27]
Either limit the number of Prestations to 20 inlines, could be tricky though because of the "at_home" feature ? give me your thoughts.

**Comment by alexolkhovskii** [comment]
We can restrict number of inline Prestation to 20 and if a user tries to add a new at_home Prestation or check at_home for already existing Prestation throw an error. 
In this way a user will be forced to remove existing Prestation if he wants to add an an_home Prestation.
What is your opinion on such solution? Will it work?

**Comment by mehditerraneen** [comment]
OK. Lets do it this way then we'll see how it goes
