### ISSUE TITLE
associate medical prescription to an Invoice

### ISSUE THREAD

**Issue by mehditerraneen** [opefitoo/nursev3#4]
Create 2 entities MedicalPrescription {prescriptor, date, file scan} - prescriptor  links to Physcian:
Physician {firstname, name, code, address, phone number }.
Store file scans in google drive eventually.

**Comment by alexolkhovskii** [comment]
I assume that in the context of this task the following should be also done:
- medical_prescription_date field should be removed from the InvoiceItem model;
- upload_scan_medical_prescription should not be added to InvoiceItem model;
The data of these fields are now kept in MedicalPrescription model.

If the above is correct, should I migrate data from the InvoiceItems' medical_prescription_date to MedicalPrescription models?

**Comment by mehditerraneen** [comment]
1. medical_prescription_date should be removed : no need to migrate previously set dates
2. a new link should be create to InvoiceItem -> MedicalPrescription
