### ISSUE TITLE
Store google Api credentials and activate sync of Contacts and Medical presciptions scans if set

### ISSUE THREAD

**Issue by mehditerraneen** [opefitoo/nursev3#7]

**Comment by alexolkhovskii** [comment]
I've added an integration with GoogleDrive storage to keep MedicalPrescriptions' uploaded files on the GDrive. Right now they are only added. Should a full sync functionality be there?
By full sync I mean that if the file changed, the previous one is removed, if MedicalPrescription removed its files is removed, etc.

To make it work you should set up a project here https://console.developers.google.com/flows/enableapi?apiid=drive
Receive a json key and put it in the "/keys" directory with the following name "gdrive_storage_key.json"

**Comment by mehditerraneen** [comment]
It's great, as a first step for the integration!
* I think that if the medical prescription is updated /removed, then yes it should be also on gdrive.
* Is there a way to make it optional if not too complex to implement
* is it possible to add a preview or a minified gif of the image file ?
